# Generated by Django 4.2.7 on 2023-11-10 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0004_about_social"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
        migrations.DeleteModel(
            name="Social",
        ),
    ]
